# Generated by Django 3.2.9 on 2021-11-21 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='the code should be matched with the correct format : 01-99', regex='/^[0-9]{1}[1-9]{1}$/gm')], verbose_name='colour code')),
                ('name', models.CharField(max_length=200, verbose_name='colour name')),
            ],
            options={
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='MotherCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='the code should be matched with the correct format : 01-99', regex='/^[0-9]{1}[1-9]{1}$/gm')], verbose_name='mother category code')),
                ('name', models.CharField(max_length=200, verbose_name='mother category name')),
            ],
            options={
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SecondCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, unique=True, validators=[django.core.validators.RegexValidator(message='the code should be matched with the correct format : 01-99', regex='/^[0-9]{1}[1-9]{1}$/gm')], verbose_name='second category code')),
                ('name', models.CharField(max_length=200, verbose_name='second category name')),
                ('mother_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcode_app.mothercategory')),
            ],
            options={
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='ThirdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, validators=[django.core.validators.RegexValidator(message='the code should be matched with the correct format : 001-999', regex='/^[0-9]{2}[1-9]{1}$/gm')], verbose_name='third category code')),
                ('name', models.CharField(max_length=200, verbose_name='third category name')),
                ('second_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcode_app.secondcategory')),
            ],
            options={
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True, validators=[django.core.validators.RegexValidator(message='the code should be matched with the correct format : 0001-9999', regex='/^[0-9]{3}[1-9]{1}$/gm')], verbose_name='store code')),
                ('name', models.CharField(max_length=200, verbose_name='store name')),
            ],
            options={
                'unique_together': {('name', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='the code should be matched with the correct format : 01-99', regex='/^[0-9]{1}[1-9]{1}$/gm')], verbose_name='size code')),
                ('size_type', models.CharField(choices=[('C', 'CLOTHING'), ('W', 'WEIGHT'), ('D', 'DIMENSIONAL')], default='CLOTHING', max_length=50, verbose_name='size type')),
                ('name', models.CharField(max_length=200, verbose_name='size name')),
            ],
            options={
                'unique_together': {('code', 'size_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True, validators=[django.core.validators.RegexValidator(message='the code should be matched with the correct format : 00001-99999', regex='/^[0-9]{4}[1-9]{1}$/gm')], verbose_name='product code')),
                ('name', models.CharField(max_length=200, verbose_name='product name')),
                ('colour', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barcode_app.colour')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='barcode_app.size')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcode_app.store')),
                ('third_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barcode_app.thirdcategory')),
            ],
            options={
                'unique_together': {('name', 'code')},
            },
        ),
    ]
