# Generated by Django 3.2.9 on 2021-11-21 18:10

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0002_auto_20211121_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='second_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barcode_app.mothercategory'), null=True, on_delete=django.db.models.deletion.CASCADE, to='barcode_app.secondcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='third_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field=smart_selects.db_fields.ChainedForeignKey(chained_field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='barcode_app.mothercategory'), null=True, on_delete=django.db.models.deletion.CASCADE, to='barcode_app.secondcategory'), null=True, on_delete=django.db.models.deletion.CASCADE, to='barcode_app.thirdcategory'),
        ),
    ]
