# Generated by Django 3.2.9 on 2021-11-21 18:18

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0004_auto_20211121_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='second_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='mother_category', chained_model_field='mother_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='barcode_app.secondcategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='third_category',
            field=smart_selects.db_fields.ChainedForeignKey(chained_field='second_category', chained_model_field='second_category', null=True, on_delete=django.db.models.deletion.CASCADE, to='barcode_app.thirdcategory'),
        ),
    ]
