# Generated by Django 3.2.9 on 2021-11-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barcode_app', '0005_auto_20211121_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(max_length=26, null=True, unique=True, verbose_name='product barcode'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('name', 'code', 'barcode')},
        ),
    ]
